- registration/src/main/java/com/teknologiumum/pesto/database/DatabaseConnection.java
- langsung inject ke private propertynya biar ngga perlu pass lewat parameter
- provide default value biar ngga perlu if statement lagi
ref: https://stackoverflow.com/a/42931711
> refactor(registration): simplify env variable injection

- landing/views/layouts/main.layout.hbs
biar lighthouse scorenya dapet 100 semua yakan
> fix(landing): add html doctype

- .github/workflows/master.yml
- .github/workflows/pr.yml
- rce/ava.config.cjs
- rce/ava.config.js
- rce/build.js
- rce/package-lock.json
- rce/package.json
- rce/src/RceService.ts
- rce/src/index.ts
- rce/src/job/job.ts
- rce/src/runtime/acquire.ts
- rce/tests/job.test.ts
- rce/tests/runtime.test.ts
- rce/tests/user.test.ts
- rce/tsconfig.json
really its just matching with the upstream private repo for teknum rce
> refactor: set runTimeout and all that jazz

- CONTRIBUTING.md
- README.md
- auth/README.md
- docker-compose.dev.yml
- landing/README.md
- rce/README.md
- rce/scripts/install.cjs
- rce/scripts/register-users.cjs
- redis/README.md
- registration/README.md
- sdk/README.md
- sdk/go/README.md
> docs: contribution guidelines

- .github/workflows/master.yml
- .github/workflows/pr.yml
Fix this issue https://github.com/teknologi-umum/pesto/actions/runs/4154814615/jobs/7187470784
> ci: fix go vcs stamping

- .github/workflows/master.yml
- .github/workflows/pr.yml
- registration/Dockerfile
- registration/Registration.csproj
> chore(registration): bump version

- .github/workflows/master.yml
images were not automatically pulled
> ci: trigger pull through compose

- auth/main.go
- rce/package-lock.json
- rce/package.json
- rce/src/index.ts
We're getting this alert:
> You have exceeded your [transaction](https://docs.sentry.io/product/performance/transaction-summary/#what-is-a-transaction) limit. We are dropping any excess events until Apr 21, 2023.
> fix(monitoring): limit sentry transaction

- sdk/dotnet/Pesto/Exceptions/PestoAPIException.cs
- sdk/dotnet/Pesto/Exceptions/PestoMonthlyLimitExceededException.cs
- sdk/dotnet/Pesto/Exceptions/PestoRuntimeNotFoundException.cs
- sdk/dotnet/Pesto/Exceptions/PestoServerRateLimitedException.cs
- sdk/dotnet/Pesto/Models/CodeOutput.cs
- sdk/dotnet/Pesto/Models/CodeRequest.cs
- sdk/dotnet/Pesto/Models/CodeResponse.cs
- sdk/dotnet/Pesto/Models/ErrorResponse.cs
- sdk/dotnet/Pesto/Models/PingResponse.cs
- sdk/dotnet/Pesto/Models/Runtime.cs
- sdk/dotnet/Pesto/Models/RuntimeResponse.cs
- sdk/dotnet/Pesto/Pesto.csproj
- sdk/dotnet/Pesto/PestoClient.cs
- sdk/dotnet/UnitTests/Mocks/PestoHttpClientMock.cs
- sdk/dotnet/UnitTests/RealPestoClientTests.cs
- sdk/dotnet/UnitTests/UnitTests.csproj
- sdk/dotnet/UnitTests/Usings.cs
add additional tests for real world pesto api
> feat(sdk): lower dotnet version

- rce/Dockerfile
if you don't know: https://stackoverflow.com/a/61990740/3153224
i've been wanting to do this for a while, haven't got time until now
current image size for rce is around 4 GB, I want to trim it down a bit
> build(rce): move everything to single stage for slimmer image

- landing/Dockerfile
update docker workflow to build the package
> chore(landing): bump docker build

- rce/Dockerfile
This reverts commit 5e8eefaa7da9db7388fe4507adb539bc217fa667.
> Revert "build(rce): move everything to single stage for slimmer image (#112)"

- .github/workflows/systems-nightly.yml
- .github/workflows/systems-pr.yml
- dogfood/.editorconfig
- dogfood/.eslintrc.json
- dogfood/LICENSE
- dogfood/README.md
- dogfood/c.test.js
- dogfood/cpp.test.js
- dogfood/go.test.js
- dogfood/javascript.test.js
- dogfood/julia.test.js
- dogfood/lua.test.js
- dogfood/package-lock.json
- dogfood/package.json
- dogfood/php.test.js
- dogfood/python.test.js
- dogfood/sqlite3.test.js
Handles #108 but we need more language, so that issue should not be closed.
please merge #111 first, I'll update the commit history, and we'll re run the CI with dogfooding involved.
> feat(dogfood): more tests

- rce/Dockerfile
- rce/Dockerfile.dev
Make sure the CI is all green before merging this.
Refer to https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
> perf(rce): lessen docker image layer size

- docker-compose.yml
refer to https://containrrr.dev/watchtower/arguments/#filter_by_enable_label
> deploy: configure watchtower label

- registration/Program.cs
> fix(registration): properly inject TrialService

- .github/workflows/systems-nightly.yml
- .github/workflows/systems-pr.yml
- landing/pnpm-lock.yaml
Tries to fix broken CI on https://github.com/teknologi-umum/pesto/pull/131 and https://github.com/teknologi-umum/pesto/pull/132
> chore(landing): bump pnpm version

- auth/.idea/.gitignore
- auth/.idea/auth.iml
- auth/.idea/modules.xml
- auth/.idea/vcs.xml
- auth/Dockerfile
- auth/authenticate.go
- auth/go.mod
- auth/go.sum
- auth/main.go
- Instrument Sentry tracing manually
- Update a few dependencies
> feat(auth): instrument tracing

- rce/src/job/job.ts
A trace wasn't going in to Sentry, now I know why.
> chore(rce): finish span on finally

- .github/workflows/systems-nightly.yml
- .github/workflows/systems-release.yml
- docker-compose.yml
We should build our own Redis instead of building it on the deployment server.
> ci: independently built database

- .github/workflows/systems-nightly.yml
- .github/workflows/systems-pr.yml
- auth/Dockerfile
- landing/Dockerfile
- rce/Dockerfile
- rce/Dockerfile.dev
- redis/Dockerfile
> chore: bump docker version

- .github/workflows/codeql.yml
- .github/workflows/sdks-nightly.yml
- .github/workflows/sdks-pr.yml
- .github/workflows/sdks-release.yml
- .github/workflows/systems-nightly.yml
- .github/workflows/systems-pr.yml
- .github/workflows/systems-release.yml
> chore: bump ci version

- .github/workflows/sdks-nightly.yml
- .github/workflows/sdks-pr.yml
- .github/workflows/secret-scan.yml
- .github/workflows/systems-nightly.yml
- .github/workflows/systems-pr.yml
CI is broken everywhere, due to changes in Trufflehog
> ci: move secret scanning to have its own dedicated job
